name: sinamon-Project-exhibition
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-production:
    runs-on: ubuntu-18.04
    steps:
            
      - name: Install
        run: npm install


      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_HOST_PRODUCTION }}
          ftp-username: ${{ secrets.FTP_USERNAME_PRODUCTION }}
          ftp-password: ${{ secrets.FTP_PASSWORD_PRODUCTION }}
          local-dir: ./
          git-ftp-args: --insecure


