name: sinamon-Project-exhibition
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-production:
    runs-on: ubuntu-18.04
    timeout-minutes: 15
#     strategy:
#       matrix:
#         node-version: [16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_HOST_PRODUCTION }}
        username: ${{ secrets.FTP_USERNAME_PRODUCTION }}
        password: ${{ secrets.FTP_PASSWORD_PRODUCTION }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
#       - uses: actions/checkout@v3
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "npm"

    
#       - name: Install modules
#         run: npm install 

#     - name: Deploy
#         uses: SamKirkland/FTP-Deploy-Action@3.1.1
#         with:
#           ftp-server: ${{ secrets.FTP_HOST_PRODUCTION }}
#           ftp-username: ${{ secrets.FTP_USERNAME_PRODUCTION }}
#           ftp-password: ${{ secrets.FTP_PASSWORD_PRODUCTION }}
#           local-dir: ../home/webtoon/webtoon
