name: sinamon-Project-exhibition
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-production:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
            
      - name: Install
        run: npm install


      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_HOST_PRODUCTION }}
          ftp-username: ${{ secrets.FTP_USERNAME_PRODUCTION }}
          ftp-password: ${{ secrets.FTP_PASSWORD_PRODUCTION }}
          local-dir: ./webtoon/
          git-ftp-args: --insecure


